CREATE TABLE IF NOT EXISTS COURSE(
    NAME VARCHAR(128),
    CREDIT INT,
    PRIMARY KEY (NAME)
);

CREATE TABLE IF NOT EXISTS SEMESTER(
    NAME VARCHAR(128),
    PRIMARY KEY (NAME)
);

CREATE TABLE IF NOT EXISTS STUDENT(
    ID VARCHAR(128),
    NAME VARCHAR(128),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ENROLLMENT(
    STUDENT_ID VARCHAR(128),
    SEMESTER VARCHAR(128),
    COURSE VARCHAR(128),
    PRIMARY KEY (STUDENT_ID,SEMESTER,COURSE)
);